package com.springboot.manager.model.generator;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class LoginExample {
    /**
     * This field was generated by MyBatis Generator, do not modify.
     * This field corresponds to the database table my_login
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator, do not modify.
     * This field corresponds to the database table my_login
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator, do not modify.
     * This field corresponds to the database table my_login
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public LoginExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator, do not modify.
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     *   my_login
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMyLoginUserIdIsNull() {
            addCriterion("my_login_user_id is null");
            return (Criteria) this;
        }

        public Criteria andMyLoginUserIdIsNotNull() {
            addCriterion("my_login_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andMyLoginUserIdEqualTo(String value) {
            addCriterion("my_login_user_id =", value, "myLoginUserId");
            return (Criteria) this;
        }

        public Criteria andMyLoginUserIdNotEqualTo(String value) {
            addCriterion("my_login_user_id <>", value, "myLoginUserId");
            return (Criteria) this;
        }

        public Criteria andMyLoginUserIdGreaterThan(String value) {
            addCriterion("my_login_user_id >", value, "myLoginUserId");
            return (Criteria) this;
        }

        public Criteria andMyLoginUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("my_login_user_id >=", value, "myLoginUserId");
            return (Criteria) this;
        }

        public Criteria andMyLoginUserIdLessThan(String value) {
            addCriterion("my_login_user_id <", value, "myLoginUserId");
            return (Criteria) this;
        }

        public Criteria andMyLoginUserIdLessThanOrEqualTo(String value) {
            addCriterion("my_login_user_id <=", value, "myLoginUserId");
            return (Criteria) this;
        }

        public Criteria andMyLoginUserIdLike(String value) {
            addCriterion("my_login_user_id like", value, "myLoginUserId");
            return (Criteria) this;
        }

        public Criteria andMyLoginUserIdNotLike(String value) {
            addCriterion("my_login_user_id not like", value, "myLoginUserId");
            return (Criteria) this;
        }

        public Criteria andMyLoginUserIdIn(List<String> values) {
            addCriterion("my_login_user_id in", values, "myLoginUserId");
            return (Criteria) this;
        }

        public Criteria andMyLoginUserIdNotIn(List<String> values) {
            addCriterion("my_login_user_id not in", values, "myLoginUserId");
            return (Criteria) this;
        }

        public Criteria andMyLoginUserIdBetween(String value1, String value2) {
            addCriterion("my_login_user_id between", value1, value2, "myLoginUserId");
            return (Criteria) this;
        }

        public Criteria andMyLoginUserIdNotBetween(String value1, String value2) {
            addCriterion("my_login_user_id not between", value1, value2, "myLoginUserId");
            return (Criteria) this;
        }

        public Criteria andMyLoginNameIsNull() {
            addCriterion("my_login_name is null");
            return (Criteria) this;
        }

        public Criteria andMyLoginNameIsNotNull() {
            addCriterion("my_login_name is not null");
            return (Criteria) this;
        }

        public Criteria andMyLoginNameEqualTo(String value) {
            addCriterion("my_login_name =", value, "myLoginName");
            return (Criteria) this;
        }

        public Criteria andMyLoginNameNotEqualTo(String value) {
            addCriterion("my_login_name <>", value, "myLoginName");
            return (Criteria) this;
        }

        public Criteria andMyLoginNameGreaterThan(String value) {
            addCriterion("my_login_name >", value, "myLoginName");
            return (Criteria) this;
        }

        public Criteria andMyLoginNameGreaterThanOrEqualTo(String value) {
            addCriterion("my_login_name >=", value, "myLoginName");
            return (Criteria) this;
        }

        public Criteria andMyLoginNameLessThan(String value) {
            addCriterion("my_login_name <", value, "myLoginName");
            return (Criteria) this;
        }

        public Criteria andMyLoginNameLessThanOrEqualTo(String value) {
            addCriterion("my_login_name <=", value, "myLoginName");
            return (Criteria) this;
        }

        public Criteria andMyLoginNameLike(String value) {
            addCriterion("my_login_name like", value, "myLoginName");
            return (Criteria) this;
        }

        public Criteria andMyLoginNameNotLike(String value) {
            addCriterion("my_login_name not like", value, "myLoginName");
            return (Criteria) this;
        }

        public Criteria andMyLoginNameIn(List<String> values) {
            addCriterion("my_login_name in", values, "myLoginName");
            return (Criteria) this;
        }

        public Criteria andMyLoginNameNotIn(List<String> values) {
            addCriterion("my_login_name not in", values, "myLoginName");
            return (Criteria) this;
        }

        public Criteria andMyLoginNameBetween(String value1, String value2) {
            addCriterion("my_login_name between", value1, value2, "myLoginName");
            return (Criteria) this;
        }

        public Criteria andMyLoginNameNotBetween(String value1, String value2) {
            addCriterion("my_login_name not between", value1, value2, "myLoginName");
            return (Criteria) this;
        }

        public Criteria andMyLoginPasswordIsNull() {
            addCriterion("my_login_password is null");
            return (Criteria) this;
        }

        public Criteria andMyLoginPasswordIsNotNull() {
            addCriterion("my_login_password is not null");
            return (Criteria) this;
        }

        public Criteria andMyLoginPasswordEqualTo(String value) {
            addCriterion("my_login_password =", value, "myLoginPassword");
            return (Criteria) this;
        }

        public Criteria andMyLoginPasswordNotEqualTo(String value) {
            addCriterion("my_login_password <>", value, "myLoginPassword");
            return (Criteria) this;
        }

        public Criteria andMyLoginPasswordGreaterThan(String value) {
            addCriterion("my_login_password >", value, "myLoginPassword");
            return (Criteria) this;
        }

        public Criteria andMyLoginPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("my_login_password >=", value, "myLoginPassword");
            return (Criteria) this;
        }

        public Criteria andMyLoginPasswordLessThan(String value) {
            addCriterion("my_login_password <", value, "myLoginPassword");
            return (Criteria) this;
        }

        public Criteria andMyLoginPasswordLessThanOrEqualTo(String value) {
            addCriterion("my_login_password <=", value, "myLoginPassword");
            return (Criteria) this;
        }

        public Criteria andMyLoginPasswordLike(String value) {
            addCriterion("my_login_password like", value, "myLoginPassword");
            return (Criteria) this;
        }

        public Criteria andMyLoginPasswordNotLike(String value) {
            addCriterion("my_login_password not like", value, "myLoginPassword");
            return (Criteria) this;
        }

        public Criteria andMyLoginPasswordIn(List<String> values) {
            addCriterion("my_login_password in", values, "myLoginPassword");
            return (Criteria) this;
        }

        public Criteria andMyLoginPasswordNotIn(List<String> values) {
            addCriterion("my_login_password not in", values, "myLoginPassword");
            return (Criteria) this;
        }

        public Criteria andMyLoginPasswordBetween(String value1, String value2) {
            addCriterion("my_login_password between", value1, value2, "myLoginPassword");
            return (Criteria) this;
        }

        public Criteria andMyLoginPasswordNotBetween(String value1, String value2) {
            addCriterion("my_login_password not between", value1, value2, "myLoginPassword");
            return (Criteria) this;
        }

        public Criteria andMyLoginCreateTimeIsNull() {
            addCriterion("my_login_create_time is null");
            return (Criteria) this;
        }

        public Criteria andMyLoginCreateTimeIsNotNull() {
            addCriterion("my_login_create_time is not null");
            return (Criteria) this;
        }

        public Criteria andMyLoginCreateTimeEqualTo(Date value) {
            addCriterion("my_login_create_time =", value, "myLoginCreateTime");
            return (Criteria) this;
        }

        public Criteria andMyLoginCreateTimeNotEqualTo(Date value) {
            addCriterion("my_login_create_time <>", value, "myLoginCreateTime");
            return (Criteria) this;
        }

        public Criteria andMyLoginCreateTimeGreaterThan(Date value) {
            addCriterion("my_login_create_time >", value, "myLoginCreateTime");
            return (Criteria) this;
        }

        public Criteria andMyLoginCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("my_login_create_time >=", value, "myLoginCreateTime");
            return (Criteria) this;
        }

        public Criteria andMyLoginCreateTimeLessThan(Date value) {
            addCriterion("my_login_create_time <", value, "myLoginCreateTime");
            return (Criteria) this;
        }

        public Criteria andMyLoginCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("my_login_create_time <=", value, "myLoginCreateTime");
            return (Criteria) this;
        }

        public Criteria andMyLoginCreateTimeIn(List<Date> values) {
            addCriterion("my_login_create_time in", values, "myLoginCreateTime");
            return (Criteria) this;
        }

        public Criteria andMyLoginCreateTimeNotIn(List<Date> values) {
            addCriterion("my_login_create_time not in", values, "myLoginCreateTime");
            return (Criteria) this;
        }

        public Criteria andMyLoginCreateTimeBetween(Date value1, Date value2) {
            addCriterion("my_login_create_time between", value1, value2, "myLoginCreateTime");
            return (Criteria) this;
        }

        public Criteria andMyLoginCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("my_login_create_time not between", value1, value2, "myLoginCreateTime");
            return (Criteria) this;
        }

        public Criteria andMyLoginUpdateTimeIsNull() {
            addCriterion("my_login_update_time is null");
            return (Criteria) this;
        }

        public Criteria andMyLoginUpdateTimeIsNotNull() {
            addCriterion("my_login_update_time is not null");
            return (Criteria) this;
        }

        public Criteria andMyLoginUpdateTimeEqualTo(Date value) {
            addCriterion("my_login_update_time =", value, "myLoginUpdateTime");
            return (Criteria) this;
        }

        public Criteria andMyLoginUpdateTimeNotEqualTo(Date value) {
            addCriterion("my_login_update_time <>", value, "myLoginUpdateTime");
            return (Criteria) this;
        }

        public Criteria andMyLoginUpdateTimeGreaterThan(Date value) {
            addCriterion("my_login_update_time >", value, "myLoginUpdateTime");
            return (Criteria) this;
        }

        public Criteria andMyLoginUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("my_login_update_time >=", value, "myLoginUpdateTime");
            return (Criteria) this;
        }

        public Criteria andMyLoginUpdateTimeLessThan(Date value) {
            addCriterion("my_login_update_time <", value, "myLoginUpdateTime");
            return (Criteria) this;
        }

        public Criteria andMyLoginUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("my_login_update_time <=", value, "myLoginUpdateTime");
            return (Criteria) this;
        }

        public Criteria andMyLoginUpdateTimeIn(List<Date> values) {
            addCriterion("my_login_update_time in", values, "myLoginUpdateTime");
            return (Criteria) this;
        }

        public Criteria andMyLoginUpdateTimeNotIn(List<Date> values) {
            addCriterion("my_login_update_time not in", values, "myLoginUpdateTime");
            return (Criteria) this;
        }

        public Criteria andMyLoginUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("my_login_update_time between", value1, value2, "myLoginUpdateTime");
            return (Criteria) this;
        }

        public Criteria andMyLoginUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("my_login_update_time not between", value1, value2, "myLoginUpdateTime");
            return (Criteria) this;
        }

        public Criteria andMyLoginStatusIsNull() {
            addCriterion("my_login_status is null");
            return (Criteria) this;
        }

        public Criteria andMyLoginStatusIsNotNull() {
            addCriterion("my_login_status is not null");
            return (Criteria) this;
        }

        public Criteria andMyLoginStatusEqualTo(Integer value) {
            addCriterion("my_login_status =", value, "myLoginStatus");
            return (Criteria) this;
        }

        public Criteria andMyLoginStatusNotEqualTo(Integer value) {
            addCriterion("my_login_status <>", value, "myLoginStatus");
            return (Criteria) this;
        }

        public Criteria andMyLoginStatusGreaterThan(Integer value) {
            addCriterion("my_login_status >", value, "myLoginStatus");
            return (Criteria) this;
        }

        public Criteria andMyLoginStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("my_login_status >=", value, "myLoginStatus");
            return (Criteria) this;
        }

        public Criteria andMyLoginStatusLessThan(Integer value) {
            addCriterion("my_login_status <", value, "myLoginStatus");
            return (Criteria) this;
        }

        public Criteria andMyLoginStatusLessThanOrEqualTo(Integer value) {
            addCriterion("my_login_status <=", value, "myLoginStatus");
            return (Criteria) this;
        }

        public Criteria andMyLoginStatusIn(List<Integer> values) {
            addCriterion("my_login_status in", values, "myLoginStatus");
            return (Criteria) this;
        }

        public Criteria andMyLoginStatusNotIn(List<Integer> values) {
            addCriterion("my_login_status not in", values, "myLoginStatus");
            return (Criteria) this;
        }

        public Criteria andMyLoginStatusBetween(Integer value1, Integer value2) {
            addCriterion("my_login_status between", value1, value2, "myLoginStatus");
            return (Criteria) this;
        }

        public Criteria andMyLoginStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("my_login_status not between", value1, value2, "myLoginStatus");
            return (Criteria) this;
        }

        public Criteria andMyLoginIsDeleteIsNull() {
            addCriterion("my_login_is_delete is null");
            return (Criteria) this;
        }

        public Criteria andMyLoginIsDeleteIsNotNull() {
            addCriterion("my_login_is_delete is not null");
            return (Criteria) this;
        }

        public Criteria andMyLoginIsDeleteEqualTo(Boolean value) {
            addCriterion("my_login_is_delete =", value, "myLoginIsDelete");
            return (Criteria) this;
        }

        public Criteria andMyLoginIsDeleteNotEqualTo(Boolean value) {
            addCriterion("my_login_is_delete <>", value, "myLoginIsDelete");
            return (Criteria) this;
        }

        public Criteria andMyLoginIsDeleteGreaterThan(Boolean value) {
            addCriterion("my_login_is_delete >", value, "myLoginIsDelete");
            return (Criteria) this;
        }

        public Criteria andMyLoginIsDeleteGreaterThanOrEqualTo(Boolean value) {
            addCriterion("my_login_is_delete >=", value, "myLoginIsDelete");
            return (Criteria) this;
        }

        public Criteria andMyLoginIsDeleteLessThan(Boolean value) {
            addCriterion("my_login_is_delete <", value, "myLoginIsDelete");
            return (Criteria) this;
        }

        public Criteria andMyLoginIsDeleteLessThanOrEqualTo(Boolean value) {
            addCriterion("my_login_is_delete <=", value, "myLoginIsDelete");
            return (Criteria) this;
        }

        public Criteria andMyLoginIsDeleteIn(List<Boolean> values) {
            addCriterion("my_login_is_delete in", values, "myLoginIsDelete");
            return (Criteria) this;
        }

        public Criteria andMyLoginIsDeleteNotIn(List<Boolean> values) {
            addCriterion("my_login_is_delete not in", values, "myLoginIsDelete");
            return (Criteria) this;
        }

        public Criteria andMyLoginIsDeleteBetween(Boolean value1, Boolean value2) {
            addCriterion("my_login_is_delete between", value1, value2, "myLoginIsDelete");
            return (Criteria) this;
        }

        public Criteria andMyLoginIsDeleteNotBetween(Boolean value1, Boolean value2) {
            addCriterion("my_login_is_delete not between", value1, value2, "myLoginIsDelete");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator, do not modify.
     *   my_login
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     *   my_login
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}